# Python Tutorial

### Standard syntax
- Python is dynamically typed -- therefore you do not need to explicitly state a variable's data type.
- Scope is based on white space, so no use of brackets for methods, loops, etc. (brackets are used for the dictionary data type)
- Do not need ```;``` to end lines
- Python does not have the *char* datatype, and there is no real distinction between char and strings.

In [3]:
x = 5
print(x)

my_string = "Hello, world"
print(my_string)

# You can get confused to you set a variable's value to something it was not named for, for example:
my_string = 3908274213408
print(f"Type of my string: {type(my_string)}")

5
Hello, world
Type of my string: <class 'int'>


### Lists

- Arrays don't exist in Python (unless you use libraries such as numpy or libraries that rely on numpy/wrapper code). Instead, Python only has lists.
- Due to dynamic typing, lists also don't have a fixed type (they are like object arrays). You can shove a whole bunch of different objects into lists. 
- List indices start at 0.

In [5]:
my_list = ["hello", 0, {"name": "Dax"}]

print(my_list) # Prints fine, no exception
print([type(item) for item in my_list])

['hello', 0, {'name': 'Dax'}]
[<class 'str'>, <class 'int'>, <class 'dict'>]


- Adding, removing, and popping elements are pretty easy

In [18]:
number_list = [0, 15, 32, 99, 852, 16]

number_list.append(82) # Adds 82 to the end of the list
print(number_list)

number_list.remove(15) # Removes the value 15
print(number_list)

del number_list[3] # Removes object at index 3
print(number_list)

number = number_list.pop(2) # Removes the value at index 2 and returns it
print(number, number_list)

number_list.reverse() # Reverses the list in place
print(number_list)

number_list.sort() # Sorts the list
print(number_list)

minimum = min(number_list)
maximum = max(number_list)
print(f"Minimum number: {minimum}, maximum number: {maximum}")

[0, 15, 32, 99, 852, 16, 82]
[0, 32, 99, 852, 16, 82]
[0, 32, 99, 16, 82]
99 [0, 32, 16, 82]
[82, 16, 32, 0]
[0, 16, 32, 82]
Minimum number: 0, maximum number: 82


- Due to the fact that lists do not have fixed datatypes, making multi-dimensional arrays are pretty simple. 
    - This is not recommended, however, if you have high-dimensionality arrays as libraries made for ndarrays (such as numpy) are wrappers for C code that are *much* more efficient.

In [19]:
my_2d_array = [[1, 2], [2, 5], ["cat", "dog"]]
print(my_2d_array)

[[1, 2], [2, 5], ['cat', 'dog']]


### Loops

Loops, in a sense, are always the "shorthand" version of loops found in other programming languages. Therefore, things like this can be done:

In [21]:
my_2d_array = [[1, 2], [2, 5], ["cat", "dog"]]

for row in my_2d_array:
    for value in row:
        print(value)

1
2
2
5
cat
dog


More standard looking for loops can be made using ```range()```

In [25]:
# A more standard for loop analogous to i = 0; i < len(list); i++
for i in range(0, len(my_2d_array), 1):
    print(my_2d_array[i])

# Shorthand exists for range as well:
for i in range(len(my_2d_array)): # Handing one parameter automatically stops at the explicit parameter, starting at 0, and iteraring 1
    print(my_2d_array[i])


[1, 2]
[2, 5]
['cat', 'dog']
[1, 2]
[2, 5]
['cat', 'dog']


### Importing Libraries
How to import libraries: You can import libraries using "import", such as ```import numpy```
There are variations on how to do this:
1. To import a library as a different variable name, use the "as" keyword
2. To import only part of a library, use the "from" keyword, such as ```from numpy import array```. You can also use ".", such as ```import numpy.array```.
    - Note that ```from numpy import *``` and ```import numpy.*``` is the same as ```import numpy```

In [27]:
import numpy as np

a = np.zeros((500, 500))
print(f"{a}\n{a.shape}")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(500, 500)
